# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17b720ba2dd844fc375aa5e44d7ebd4f389af834df5adf21571d1acc0193f1ee7e21e54cba6164e2362da4140f0d285c9a559eda1237a61c0122d1b0335cbd55

test:
  secret_key_base: 3fa4699955325ee772b8c7c46a1f3fa1461b96a6c39bdbec8807749d90195f22c3db373d4143e0c3fd9463e99724303bda1c721e1c3cb4c9d8839d84ab60ce7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
